In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df =pd.read_csv("practwo.csv")
df

area   bedrooms  age   price
0   2600       3.0   20  550000
1   3000       4.0   15  565000
2   3200       NaN   18  610000
3   3600       3.0   30  680000
4   4000       5.0    8  725000

In [4]:
import math
median_bedroom =math.floor(df.bedrooms.median())
median_bedroom

3

In [12]:
df.bedrooms= df.bedrooms.fillna(median_bedroom)

In [13]:
df

area   bedrooms  age   price
0   2600       3.0   20  550000
1   3000       4.0   15  565000
2   3200       3.0   18  610000
3   3600       3.0   30  680000
4   4000       5.0    8  725000

In [17]:
df.columns = df.columns.str.strip()

reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [18]:
reg.predict([[3000,3,40]])

array([597200.])

In [19]:
reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [21]:
reg.intercept_


173112.5

In [23]:
143.625*3000-6762.5*3+40*337.5+173112.5

597200.0

In [24]:
reg.predict([[2500,4,5]])

array([506812.5])

In [25]:
reg.predict([[2600,3,20]])

array([533000.])

# Excercise

In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [94]:
daf= pd.read_csv('extwo.csv')
daf

experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9   50000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [95]:
daf.experience = daf.experience.fillna("zero")
#wrd2 number garera median nikalera halna ni sakinxa

In [96]:
daf

experience  test_score(out of 10)  interview_score(out of 10)  salary
0       zero                    8.0                           9   50000
1       zero                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [97]:
import math
mean_test_score =math.floor(daf['test_score(out of 10)'].mean())
mean_test_score

7

In [98]:
daf['test_score(out of 10)']=daf['test_score(out of 10)'].fillna(mean_test_score)
daf.experience = daf.experience.apply(w2n.word_to_num)
daf

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9   50000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    7.0                           7   72000
7          11                    7.0                           8   80000

In [99]:
regn=linear_model.LinearRegression()
regn.fit(daf[['experience','test_score(out of 10)','interview_score(out of 10)']],daf.salary)

LinearRegression()

In [100]:
regn.predict([[11,9,10]])

array([88604.2181719])

In [76]:
regn.predict([[0,0,0]])

array([14992.65144669])