In [2]:
import pandas as pd
import numpy as np


In [8]:
df=pd.read_csv('homeprices.csv')
df.columns = df.columns.str.strip()

In [16]:
dummies=pd.get_dummies(df.town)
dummies

monroe township    monroe township     robinsville   west windsor   \
0                   1                   0             0              0   
1                   0                   1             0              0   
2                   0                   1             0              0   
3                   0                   1             0              0   
4                   0                   1             0              0   
5                   0                   0             0              0   
6                   0                   0             0              0   
7                   0                   0             0              1   
8                   0                   0             0              1   
9                   0                   0             1              0   
10                  0                   0             1              0   
11                  0                   0             1              0   
12                  0                   0             1              0   

    west windsor        
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    1  
6                    1  
7                    0  
8                    0  
9                    0  
10                   0  
11                   0  
12                   0

In [30]:
merged=pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township    monroe township     \
0    monroe township    2600  550000                  1                   0   
1   monroe township     3000  565000                  0                   1   
2   monroe township     3200  610000                  0                   1   
3   monroe township     3600  680000                  0                   1   
4   monroe township     4000  725000                  0                   1   
5   west windsor        2600  585000                  0                   0   
6   west windsor        2800  615000                  0                   0   
7        west windsor   3300  650000                  0                   0   
8        west windsor   3600  710000                  0                   0   
9         robinsville   2600  575000                  0                   0   
10        robinsville   2900  600000                  0                   0   
11        robinsville   3100  620000                  0                   0   
12        robinsville   3600  695000                  0                   0   

    robinsville   west windsor   west windsor        
0              0              0                   0  
1              0              0                   0  
2              0              0                   0  
3              0              0                   0  
4              0              0                   0  
5              0              0                   1  
6              0              0                   1  
7              0              1                   0  
8              0              1                   0  
9              1              0                   0  
10             1              0                   0  
11             1              0                   0  
12             1              0                   0

In [42]:
merged.columns = merged.columns.str.strip()

final=merged.drop(['town','west windsor'],axis=1)
final

area   price  monroe township  monroe township  robinsville
0   2600  550000                1                0            0
1   3000  565000                0                1            0
2   3200  610000                0                1            0
3   3600  680000                0                1            0
4   4000  725000                0                1            0
5   2600  585000                0                0            0
6   2800  615000                0                0            0
7   3300  650000                0                0            0
8   3600  710000                0                0            0
9   2600  575000                0                0            1
10  2900  600000                0                0            1
11  3100  620000                0                0            1
12  3600  695000                0                0            1

In [44]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
final.columns = final.columns.str.strip()


In [47]:
X = final.drop('price',axis='columns')
X

area  monroe township  monroe township  robinsville
0   2600                1                0            0
1   3000                0                1            0
2   3200                0                1            0
3   3600                0                1            0
4   4000                0                1            0
5   2600                0                0            0
6   2800                0                0            0
7   3300                0                0            0
8   3600                0                0            0
9   2600                0                0            1
10  2900                0                0            1
11  3100                0                0            1
12  3600                0                0            1

In [49]:
Y = final.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [52]:
model.fit(X,Y)


LinearRegression()

In [65]:
model.predict([[2600,1,1,0]])

array([505536.48068671])

In [66]:
model.score(X,Y)

0.9618138719815559

## onehot encoder

In [68]:
df


town  area   price
0    monroe township    2600  550000
1   monroe township     3000  565000
2   monroe township     3200  610000
3   monroe township     3600  680000
4   monroe township     4000  725000
5   west windsor        2600  585000
6   west windsor        2800  615000
7        west windsor   3300  650000
8        west windsor   3600  710000
9         robinsville   2600  575000
10        robinsville   2900  600000
11        robinsville   3100  620000
12        robinsville   3600  695000

In [70]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()


In [72]:
dfle=df
dfle.columns = dfle.columns.str.strip()
dfle.town=le.fit_transform(dfle.town)
dfle


town  area   price
0      0  2600  550000
1      1  3000  565000
2      1  3200  610000
3      1  3600  680000
4      1  4000  725000
5      4  2600  585000
6      4  2800  615000
7      3  3300  650000
8      3  3600  710000
9      2  2600  575000
10     2  2900  600000
11     2  3100  620000
12     2  3600  695000

In [82]:
X=dfle[['town','area']].values
X

array([[   0, 2600],
       [   1, 3000],
       [   1, 3200],
       [   1, 3600],
       [   1, 4000],
       [   4, 2600],
       [   4, 2800],
       [   3, 3300],
       [   3, 3600],
       [   2, 2600],
       [   2, 2900],
       [   2, 3100],
       [   2, 3600]])

In [91]:
Y= dfle.price.values
Y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [92]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [94]:
X= ct.fit_transform(X)
X

array([[0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.3e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03]])

In [97]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03]])

In [100]:
model.fit(X,Y)

LinearRegression()

In [103]:
model.predict([[0,0,1,3400]])

array([693346.56834941])

In [104]:
model.score(X,Y)

0.9650148713921218